### ISSUE TITLE
I want to join you guys!

### ISSUE THREAD

**Issue by JDScript** [JeremyHe1209/ByteBlitz#2]
!.!

**Comment by JeremyHe1209** [comment]
Thank you for your interest in our project!
I don't have much time at weekdays. So let's talk more at the weekend.
I don't really know who you are, but I have some questions.
- Who are you? (Umm, like ``Are you Chinese?``, ``Are you a university student?`` ......)
- How do you know this project?
- Why do you want to join us?
- If you are a member of this project, what will you do in the future?
Waiting for your reply......
